### PR TITLE
Edit/Update Join us content

### PR DESCRIPTION
**Pull request by Erin-Cecele**
Thank you for contributing to the Quire Documentation & Website! Please complete the form below to submit your pull request for review.

*For the Title of this pull request, please use the format "Type/Issue-#: Brief description." For Type, the options are Edit, Add, Translate. Issue-# is only needed if this pull request addresses an existing issue.*

### Checklist 

Please put an X within the brackets that apply `[X]`.

- [X] I have read the [CONTRIBUTING.md](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) file.

- [X] I have made my changes in a new branch and not directly in the main branch

- [X] I am requesting feedback on a draft pull request

### Is this pull request related to an open issue? If so, what is the issue number?

No

### Please describe the goal of this pull request and the changes that were made.

Update Join Us page so that it is more accurate and will hopefully get more traffic. 

- Change name to Get Involved
- Remove content / Add content
- Remove Undraw images
- Add Openemoji images 

### Additional Comments

@geealbers This is still a little rough, but I'm hoping we can take a look at it together next week.

### CODE REVIEW

**Comment by Erin-Cecele** [comment]
Hi @dimrkh I would love your feedback on the changes being made to the Join us Page of the website. I've added you as a reviewer. Pull down my branch to view the changes locally. We can either set-up a time to chat through things or feel free to go in and make tweaks yourself. Thank you!

**Comment by dimrkh** [comment]
@Erin-Cecele This looks great! Please take a look and see what you think; happy to have a call or keep going back and forth. I just revised some of the language to emphasize active voice and retain stylistic consistency across the segments. I also made some changes in the icons, but I think there are great reasons for keeping all of your original ones. Happy to discuss of course!

**Comment by Erin-Cecele** [comment]
Thank you @dimrkh your edits were fantastic! I made a few more tweaks to some wording and changed out a few illustrations but happy with where it's landed. 

@geealbers This is ready for you to review.

**Review by geealbers — APPROVED** [review]
Looks good to me!

**Pull request merged**
