### PR TITLE
Edit/#641: add fact sheet and logo

### PR DESCRIPTION
**Pull request by Erin-Cecele**
Thank you for contributing to the Quire Documentation & Website! Please complete the form below to submit your pull request for review.

*For the Title of this pull request, please use the format "Type/Issue-#: Brief description." For Type, the options are Edit, Add, Translate. Issue-# is only needed if this pull request addresses an existing issue.*

### Checklist 

Please put an X within the brackets that apply `[X]`.

- [X] I have read the [CONTRIBUTING.md](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) file.

- [X] I have made my changes in a new branch and not directly in the main branch

- [X] I am requesting feedback on a draft pull request

### Is this pull request related to an open issue? If so, what is the issue number?

#641 

### Please describe the goal of this pull request and the changes that were made.

Update fact sheet on home page 

### Additional Comments

@geealbers I also noticed that the logo on the website appears to be the old one. I tried to update to the new logo in this PR by replacing what I found in the `static/img/` folder but I'm not seeing these changes reflected on the website. Please help or advise.

### CODE REVIEW

**Review by geealbers — COMMENTED** [review]
The logo file you uploaded is a little smaller than the original. Do you know where this is being used? Will the size difference have a negative impact on the layout anywhere?

**Comment by Erin-Cecele** [comment]
@geealbers I was trying to update the logos at the top left corner and the very bottom of the page as they are the old logo. 

Adding this new image should be reflected at the bottom of the homepage, but for some reason, it's not. Also not sure what to do about the different size. This is the quire_logo_positive_small_RGB.png that Jeffrey gave us. 

Screen Shot 2023-01-27 at 3 47 20 PM

I also can't figure out how the black logo at the top left is being pulled in. I can't find anything with the id `homepage-banner-image`.

Screen Shot 2023-01-27 at 3 53 40 PM

**Comment by geealbers** [comment]
@Erin-Cecele when I preview this PR, I'm seeing the new logo (with the TM in the lower right instead of the upper right) in both the top left corner of the site, and at the home page as expected. Can you try again, maybe with a hard refresh to clear your browser cache?

**Comment by Erin-Cecele** [comment]
Oh my god! The hard refresh worked ::facepalm:: Well, looks like the fact sheet was still a bit outdated. So, it's been updated!

**Review by geealbers — APPROVED** [review]

**Pull request merged**
