### PR TITLE
Edit/get involved

### PR DESCRIPTION
**Pull request by Erin-Cecele**
Thank you for contributing to the Quire Documentation & Website! Please complete the form below to submit your pull request for review.

*For the Title of this pull request, please use the format "Type/Issue-#: Brief description." For Type, the options are Edit, Add, Translate. Issue-# is only needed if this pull request addresses an existing issue.*

### Checklist 

Please put an X within the brackets that apply `[X]`.

- [X] I have read the [CONTRIBUTING.md](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) file.

- [X] I have made my changes in a new branch and not directly in the main branch

- [X] I am requesting feedback on a draft pull request

### Is this pull request related to an open issue? If so, what is the issue number?

No

### Please describe the goal of this pull request and the changes that were made.

Update the website with new bug-reporting instructions.

### Additional Comments

@geealbers, what do you think of the line I added at the end of each page pointing people to the bug-reporting instructions? Is it helpful? Is there a better way to do it?

### CODE REVIEW

**Comment by geealbers** [comment]
I like the idea of the line on the bottom of each page. Can you provide a screenshot of how it looks now? I'm wondering if it should be visually set off in some way. Perhaps by putting it in a different color text, a different size text or font, or adding a rule line or just some extra margin above. You could toy with some custom.css if you agree.

Also, I think this should be added in through one of the page templates rather than having it copied individually in every markdown file. Do you want to poke around and see if you can figure out a way to do that? (Or I can later.)

**Comment by Erin-Cecele** [comment]
Here's the screenshot. I completely agree about having them visually set off. 

Screen Shot 2023-06-30 at 2 38 10 PM

And I agree that having it added to the website template is more efficient.

I'll see what I can figure out for both the CSS and the template.

**Comment by Erin-Cecele** [comment]
@geealbers I removed the bug reporting note from this PR, and instead it's just edits to the Get Involved page. OK to merge?

**Comment by Erin-Cecele** [comment]
Oops also wanted to mention I created an issue for us to address the bug reporting note: #688

**Review by geealbers — APPROVED** [review]
Yes, good to merge

**Pull request merged**
