### PR TITLE
Edit zooming-images.md

### PR DESCRIPTION
**Pull request by Erin-Cecele**

### CODE REVIEW

**Review by geealbers — APPROVED** [review]
Are there any words we should link/add glossary definitions to? I was wondering about JSON specifically, but there could be others.

**Comment by Erin-Cecele** [comment]
Good call. I can definitely create a glossary entry for JSON. The only other one that crossed my mind is Javascript but it's not mentioned too frequently throughout the docs, so maybe not.

**Comment by Erin-Cecele** [comment]
I took my best shot at a JSON definition but it may need some finessing

**Comment by geealbers** [comment]
The definition maybe could be even more basic, but I don't have a better idea so I'd say go ahead and merge it.

And we're having the same trouble here with the Netlify build as we were on the showcase branch. But we can ignore it. It will sort itself out once we merge.

**Pull request merged**
