### PR TITLE
Docs/design guide ed

### PR DESCRIPTION
**Pull request by Erin-Cecele**
What do you think of this as an option for the Design Guide? I think it's a nice example of everything discussed in the Cheatsheet.

### CODE REVIEW

**Review by geealbers — COMMENTED** [review]
Yeah, I think this looks terrific. What do you think about moving it to the top of the cheat sheet page though? It feels like a nice overview of markdown, yaml and shortcodes. So if people see it first, they can then scroll down for more info on each if they need to. And I'd hate for people to miss it.

I'd also like to see Audrey get more direct credit for it. Maybe worth re-doing these commits and adding her as a co-author? Or if you have some other way of tagging her in the git record too, that's fine.

**Comment by Erin-Cecele** [comment]
I'm not quite sure what you mean by re-doing them. Would that mean reverting them and doing them again with Audrey tagged? Doesn't look like there is an easy way to add to the git record after the fact.

**Comment by geealbers** [comment]
Yeah, I think if there's no way to do it now, it would be essentially starting a new branch, copying these changes in with her tagged, and then submitting a new PR and trashing this one. 😬

**Comment by Erin-Cecele** [comment]
Closed by PR #438

**Pull request closed without merging**
