### PR TITLE
clarify id instructions

### PR DESCRIPTION
**Pull request by Erin-Cecele**
Thank you for contributing to the Quire Documentation & Website! Please complete the form below to submit your pull request for review.

*For the Title of this pull request, please use the format "Type/Issue-#: Brief description." For Type, the options are Edit, Add, Translate. Issue-# is only needed if this pull request addresses an existing issue.*

### Checklist 

Please put an X within the brackets that apply `[X]`.

- [X] I have read the [CONTRIBUTING.md](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) file.

- [X] I have made my changes in a new branch and not directly in the main branch

- [ ] I am requesting feedback on a draft pull request

### Is this pull request related to an open issue? If so, what is the issue number?

Yes: https://github.com/thegetty/quire/issues/869 

### Please describe the goal of this pull request and the changes that were made.

Update recently revised guidelines to include "cannot start with a number / can only start with a lowercase letter".

### CODE REVIEW

**Review by geealbers — COMMENTED** [review]
Do we talk about `id`s in contexts other than figures elsewhere in the docs? I think we probably should be consistent everywhere that they should always be lowercase and use hyphens and nothing else.

**Comment by Erin-Cecele** [comment]
well ... now that I think of it, citation `id`'s do have spaces in them. I tested numbers, underscores, and periods but I guess I didn't test spaces within figure `id`s. Is there any reason a space would work in a citation `id` versus a figure `id`? Or is your point more that we should keep the messaging uniform across `id` types regardless?

**Comment by Erin-Cecele** [comment]
@geealbers per our meeting this morning, can I merge this? I opened two additional issues to keep track of the work not yet done: #715 and #716.

**Review by geealbers — APPROVED** [review]
Yes, good to merge

**Pull request merged**
