### PR TITLE
Add/tutorial images and demo

### PR DESCRIPTION
**Pull request by Erin-Cecele**
Thank you for contributing to the Quire Documentation & Website! Please complete the form below to submit your pull request for review.

*For the Title of this pull request, please use the format "Type/Issue-#: Brief description." For Type, the options are Edit, Add, Translate. Issue-# is only needed if this pull request addresses an existing issue.*

### Checklist 

Please put an X within the brackets that apply `[X]`.

- [X] I have read the [CONTRIBUTING.md](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) file.

- [X] I have made my changes in a new branch and not directly in the main branch

- [X] I am requesting feedback on a draft pull request

### Is this pull request related to an open issue? If so, what is the issue number?

#631 

### Please describe the goal of this pull request and the changes that were made.

Update tutorial content and images 

### Additional Comments

Also using this PR to add the demo video. HELP NEEDED: Quire is confused about the `media_id` in the same way that Campaign Manager was. I'm using the id with the slash in it, and I'm getting an "invalid embed code" error. See commit 8cb45ecd.

### CODE REVIEW

**Comment by geealbers** [comment]
If you unzip and save the attached file to `layouts/partials/figures/media-types/vimeo.html` in the repo, _I think_ the two-part vimeo id should work.

[vimeo.html.zip](https://github.com/thegetty/quire-docs/files/11105683/vimeo.html.zip)

**Comment by Erin-Cecele** [comment]
Thanks @geealbers I only see layouts/partials/ and then this... 

image

**Comment by Erin-Cecele** [comment]
ok yay that did the trick!

**Comment by Erin-Cecele** [comment]
@geealbers Let me know when this is good to merge. Thank you!

**Review by geealbers — APPROVED** [review]

**Pull request merged**
