### PR TITLE
Ed split deploy WIP

### PR DESCRIPTION
**Pull request by Erin-Cecele**
Made a lot of changes to the deploy page, including adding GH Pages (it actually wasn't as complicated as I thought). I also radically changed the sub-modules and LFS sections because they were designed primarily for Netlify but could also easily apply to GH Pages. I'm open to other options and adding back more information, I mostly just wanted to try this structure out and see what you thought. Very much a WIP!

### CODE REVIEW

**Comment by geealbers** [comment]
Yes, we should definitely split things up like you're doing here. A few notes:

I really like how the Output page starts with a very short paragraph before getting into the main topics. It's a nice little abstract. I'd just add something to the end of that paragraph to point people to the Deploy page... "Once your outputs are ready, read more about deploying your project to the web." Or something like that.

I'd then love to see the Deploy page follow the same structure with a brief paragraph (you can almost use the one there), followed by a new section called "Basic Deploy" with that info, and then move to Netlify and GH pages.

You don't really need the links about learning and being comfortable in GitHub until after the instructions for Netlify's manual deploy (which doesn't require GitHub).

Let's be sure to work into the Manual Netlify instructions something from this post https://answers.netlify.com/t/support-guide-my-drag-and-drop-deploy-is-stuck-in-uploading-status/112, which details some limitations that we didn't know about before.

The GitHub Best Practices section doesn't feel right to me on this page. I think because it's not really parallel with the overall structure of the page, which is otherwise broken down into different deploy options. I'd put it all on the GitHub page and link to it as needed.

**Comment by Erin-Cecele** [comment]
Sounds good. I just remembered that I needed to add something to the GH pages section regarding the fonts. Can you remind me what that was?

**Comment by geealbers** [comment]
Oh yeah. For fonts and GH pages, it was that the paths needed to be updated in that webpack file. I think I have it in an email somewhere. Will forward it to you

**Comment by Erin-Cecele** [comment]
Just made some updates. I also renamed the markdown file. Hopefully you can still see what precise changes I made. 

- I added note to output page pointing to deploy (and vice versa on deploy page)
- I created a separate Basic Deploy section in addition to Netlify and GH Pages to make the page structure more closely reflect the output page. 
- I had trouble figuring out where best to put the "learn about GitHub" links. If I move it down below Manual Deploy and either have it just under Continuous Deploy or just under GH Pages then I feel like it gets lost if someone chooses a different option. I could put it at the end of Continuous just before GH Pages but that also feels weird. Open to suggestions. 
- I removed the Git Best Practice info and put it in Project Management with GitHub .... however, I went to delete the Netlify page and there is still a lot of info in there that I can't figure out how to integrate: Netlify Build Configuration, Alter or Add Another Command, Private Submodules, and Netlify and Git LFS. What should I do with this info?
- Finally, I saw your email with Natalie re: webpack fonts note for GitHub Pages... I assumed komai/fonts/ or komai/img/ means you need to add in the project name before /font and /img.
- In thinking about my conversation with the editors, it struck me that we ask people to make changes like the above but we don't really explain why. I know that means adding more text but it might be helpful. What do you think?

**Comment by geealbers** [comment]
This all looks good to merge now, and then we can keep refining and tweaking later. 

In answer to some of your questions ... The Learn about GitHub stuff works pretty well where it is as an alert box like you have it. You can make the Netlify page `online: false` like we talked about. And I think you're right and it's fine to add a little bit of explanation here or there, especially where we're asking users to do something particularly odd or particular, but we can probably keep it pretty short. Even something like this might make a difference:

> So that the site fonts display properly, change line 80 to outputPath: "[YOUR-PROJECT-DIRECTORY-NAME]/img/" And change line 92 to outputPath: "[YOUR-PROJECT-DIRECTORY-NAME]/fonts/".

Finally, just remember to add in warning language about the limitations of Netlify Drop when you can.

And I just saw there's a typo in deploy: "each time oyu make an update"

**Comment by Erin-Cecele** [comment]
@geealbers Ok great. I made a few more changes. I'm going to merge but please feel free to pass along additional edits as you come across or think of them. Thanks!

**Pull request merged**
