### PR TITLE
Add/360 degree docs

### PR DESCRIPTION
**Pull request by geealbers**
Thank you for contributing to the Quire Documentation & Website! Please complete the form below to submit your pull request for review.

*For the Title of this pull request, please use the format "Type/Issue-#: Brief description." For Type, the options are Edit, Add, Translate. Issue-# is only needed if this pull request addresses an existing issue.*

### Checklist 

Please put an X within the brackets that apply `[X]`.

- [X] I have read the [CONTRIBUTING.md](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) file.

- [X] I have made my changes in a new branch and not directly in the main branch

- [ ] I am requesting feedback on a draft pull request

### Is this pull request related to an open issue? If so, what is the issue number?

#684 

### Please describe the goal of this pull request and the changes that were made.

Add documentation for the new 360-degree image sequence work.

### Additional Comments

I'm also suggesting we update the title of the zooming image page so that all the figure-related pages start with "Figure Images" which (I think) makes it easier to scan the TOC and menu on the site and see these as related. (If we were in the 11ty version of Quire, we could do this by having them all in a sub-directory, but this naming seems ok for now.)

@Erin-Cecele if you're going to test this out yourself, I can give you some image sequences to play with. Just let me know what you want/need.

### CODE REVIEW

**Comment by Erin-Cecele** [comment]
I added some comments to this PR and submitted my own PR of edits I made to your branch (rather than making you go back and do all the work.) Let me know if this method works ok for you.

I would suggest adding an example of a 360-degree rotating image and also a sequential image like the Muybridge (unless there's a copyright issue with that example). OR if we did want to put the two starter projects on our website, we could link to those relevant sections rather than duplicating the word and weighing the website down with extra images.

**Comment by geealbers** [comment]
Making your edits as a separate PR to this one worked like a treat. Great idea, and thank you.

We can't add examples to the docs because the docs are v0. I definitely agree we need some though, so I've resurrected a new demo site I'd started back when we were documenting accordions. With the thought to replace what's at https://quire.getty.edu/demo/. I'm hoping to have a draft of that demo site to share with you later today

**Comment by geealbers** [comment]
@Erin-Cecele, I just pushed a couple last commits to add a link to the demo site, make the text less specific to 360s, and add a section at the bottom I realized was missing, about displaying a sequence image on a page. Can you give this one last look before we merge it?

**Review by Erin-Cecele — APPROVED** [review]
Looks fantastic!

**Comment by Erin-Cecele** [comment]
I guess my only feedback is we might want to consider whether there is a better visual queue for the demo site than a box tip.

{{< q-class "box tip" >}}
View some [examples on our demo site](https://quire.getty.edu/demo/figures/sequences/).
{{< /q-class >}}

**Comment by geealbers** [comment]
Agreed that there's probably a better way to feature the demo site, and also that we can figure it out in the future.

Merging this in now.

**Pull request merged**
