### PR TITLE
Add/caa info page

### PR DESCRIPTION
**Pull request by Erin-Cecele**
Thank you for contributing to the Quire Documentation & Website! Please complete the form below to submit your pull request for review.

*For the Title of this pull request, please use the format "Type/Issue-#: Brief description." For Type, the options are Edit, Add, Translate. Issue-# is only needed if this pull request addresses an existing issue.*

### Checklist 

Please put an X within the brackets that apply `[X]`.

- [X] I have read the [CONTRIBUTING.md](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) file.

- [X] I have made my changes in a new branch and not directly in the main branch

- [X] I am requesting feedback on a draft pull request

### Is this pull request related to an open issue? If so, what is the issue number?

No

### Please describe the goal of this pull request and the changes that were made.

Create VERY rough draft of CAA landing page that will be up from December 2021 through late February 2022

### Additional Comments

This is a VERY rough draft to be reviewed together on Thursday.

### CODE REVIEW

**Comment by geealbers** [comment]
This is looking good. Rather than inserting them as images, could we include the community projects using the shortcode? These aren't the right projects, I just grabbed this from the home page as an example:

```
{{< q-showcase projects="50_x_50, duke_wired, french_paintings, ray_komai, tilt_art_community" sort="false" >}}

```

And if we want to clarify what is about these projects that's relevant, we could add headings or other supportive text around (before/after) the shortcode

**Comment by Erin-Cecele** [comment]
Ah ok that's a good call. just updated.

**Review by geealbers — APPROVED** [review]

**Comment by geealbers** [comment]
Oh, one last thing! Should we say shat CAA is? Just realized we only ever use the abbreviation

**Comment by Erin-Cecele** [comment]
Just updated. Are we ready to merge it?

**Comment by geealbers** [comment]
merge away!

**Pull request merged**
